language: java
jdk:
- oraclejdk8
sudo: false
install: true
notifications:
  email:
    recipients:
    - David.Dunphy@verint.com
    on_success: never
    on_failure: change
branches:
  only:
  - master
before_install:
- chmod +x gradlew
script:
- "./gradlew sonarqube"
addons:
  sonarqube:
    organization: rddunphy-github
    token:
      secure: 1RcIaBM+ceErTppOr0DGOv8dkQkQPUsBfU63fM7sPdAko4uoVQVGmwILdH8G6OEA/V8pwgtjcydckAO5n0j4rEKace9Gdelv8kfUzNvxAosa5XGi+YA7zDdJhbGl280e2Skiz+Z10Z3iO7G8Zi7DSmwCi1dK0ocqtckidXFEspACVhDnoDdC3YIAGt4tva7dt/qlhx/Sc3aVmTy1oPb8qoihS3sl4e0NcI/+0Hq+i5QxgBWhgspw9JNQylC+nGrN0Fzt0qjnUBOpteHWuYQR/Bqrxs/JZvds0qUUWr/gjDtei6eNkh6zvlFZlinCIxwqpYEIf6f9t2eYnNznAFw/sEFYxAHaCS6RzetFWm+dTwM91l9ihCbPJfh5ZhZQYNRIpLAEJwJSPeCBbs5OyyQTb2NBakTvWWUW8Jnebm0Cxbgbf7lrtUlqg6/omCYQFCrywsNz21EccGLXhm2Mqft3wtSBe+8JNL+ef0vIo0/IxGpgquZGgL1eohPu55Gg5PDOCHOKAP9Hv8dc1HUnvwoehKz8ETZkb+3h40XFkMzKJz12viGJ8uC9tdw8GFaCbgSki/K7G9DoGSKsLf5bPo22rDZjfBjbCIuGMtGEZRLwapCa+cApl/cKxDLZUQm3/02IzFUeLM4zhgiDK0mL9cdrGQ54jgR7/MYSl76dN32wb98=
cache:
  directories:
  - "$HOME/.m2/repository"
  - "$HOME/.sonar/cache"
  - "$HOME/.gradle"
  - ".gradle"